stages:
  - test
  - build

lint:
  image: node:10.15-alpine
  stage: test
  variables:
    DATABASE_TEST_URL: "mongodb://mongo/dbname"
  services:
    - mongo
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
    - node_modules
  script:
    - npm config set unsafe-perm true
    - apk --no-cache add make gcc g++ python git
    - npm i
    - npm run audit
    - npm run lint
#    - npm run test
  tags:
    - docker

build.develop:
  stage: build
  variables:
    NODE_APP_INSTANCE: development
    NODE_ENV: development
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules
  script:
    - npm config set unsafe-perm true
    - npm i
    - npm run migrate
    - npm run doc
    - pm2 delete pm2.json
    - pm2 run pm2.json
  only:
    - develop
  tags:
    - develop
  environment:
    name: development

build.master:
  stage: build
  variables:
    NODE_APP_INSTANCE: stage
    NODE_ENV: stage
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules
  script:
    - npm i
    - npm delete migrate
    - pm2 run pm2.json
  only:
    - master
  tags:
    - master
  environment:
    name: stage
