stages:
  - test
  - build

test:
  image: node:10.15-alpine
  stage: test
  variables:
    DATABASE_TEST_URL: "mongodb://mongo/dbname"
  services:
    - mongo
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
    - node_modules
  script:
    - npm config set unsafe-perm true
    - apk --no-cache add make gcc g++ python git
    - npm i
    - npm run audit
    - npm run lint
#    - npm run test
  tags:
    - docker


build.develop:
  stage: build
  variables:
    NODE_APP_INSTANCE: development
    NODE_ENV: development
    STAGE: develop
    API_PORT: 16456
    MONGODB_PORT: 16457
  script:
    - docker build -t 645.echodb .
    - docker-compose -p 645.echodb.develop up -d
  only:
    - develop
  tags:
    - pp-develop
  environment:
    name: develop
    url: https://645-echodb.pixelplex-test.by


build.master:
  stage: build
  variables:
    NODE_APP_INSTANCE: master
    NODE_ENV: master
    STAGE: master
    API_PORT: 26456
    MONGODB_PORT: 26457
  script:
    - docker build -t 645.echodb .
    - docker-compose -p 645.echodb.develop up -d
  only:
    - master
  tags:
    - pp-stage
  environment:
    name: master
    url: https://645-echodb.pixelplexlabs.com
