stages:
  - build
  - deploy


build:
  stage: build
  variables:
    NODE_APP_INSTANCE: $CI_COMMIT_REF_NAME
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - master
    - develop
  tags:
    - echo-linux


deploy:
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - if [ "$CI_COMMIT_REF_NAME" != "master" ]; then export PORT=36456; fi
    - if [ "$CI_COMMIT_REF_NAME" != "master" ]; then export MONGODB_ADDR="127.0.0.1:36457"; fi
  variables:
    CI_FULL_REGISTRY: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    PORT: 26456
    NODE_APP_INSTANCE: $CI_COMMIT_REF_NAME
    NODE_ENV: production
    MONGODB_ADDR: 127.0.0.1:26457
  script:
    - docker-compose -p echodb-$CI_COMMIT_REF_NAME up -d
  only:
    - develop
    - master
  tags:
    - echo-linux
