version: '3'
services:
  redis:
    image: redis:5.0.4-alpine
    restart: always
    ports:
      - 6379:6379
  mongo:
    image: mongo:4.0
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_DATA_DIR=/data/mongo-db
    command: mongod --smallfiles
    restart: always
    ports:
      - 27017:27017
volumes:
  mongodb: